name: Deploy to PROD

on:
  push:
    branches:
      - main

jobs:
  BuildApp:
    uses: ./.github/workflows/BuildApp.yml
    with:
      image_name: monthly-app
    secrets:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
